---
name: Create RPMs

on:
  release:
    types: [created]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build RPM package for EL6
        id: rpm_build_el6
        uses: redwain/rpmbuild@el6
        with:
          spec_path: "packaging/convert2rhel.spec"

       - name: Upload EL6 RPM as release asset
        id: upload_release_asset_el6
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ${{ steps.rpm_build_el6.outputs.srpm_path }}
            asset_name: ${{ steps.rpm_build_el6.outputs.srpm_name }}
            asset_content_type: ${{ steps.rpm_build_el6.outputs.content_type }}

      - name: Build RPM package for EL7
        id: rpm_build_el7
        uses: redwain/rpmbuild@el7
        with:
          spec_path: "packaging/convert2rhel.spec"

      - name: Upload EL7 RPM as release asset
        id: upload_release_asset_el7
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ${{ steps.rpm_build_el7.outputs.srpm_path }}
            asset_name: ${{ steps.rpm_build_el7.outputs.srpm_name }}
            asset_content_type: ${{ steps.rpm_build_el7.outputs.content_type }}

      - name: Build RPM package for EL8
        id: rpm_build_el8
        uses: redwain/rpmbuild@centos8
        with:
          spec_path: "packaging/convert2rhel.spec"
        
      - name: Upload EL8 RPM as release asset
        id: upload_release_asset_el8
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ${{ steps.rpm_build_el8.outputs.source_rpm_path }}
            asset_name: ${{ steps.rpm_build_el8.outputs.source_rpm_name }}
            asset_content_type: ${{ steps.rpm_build_el8.outputs.rpm_content_type }}
